### PR TITLE
Bump FRR to 9.1.0

### PR DESCRIPTION
**Pull request by fedepaol**
**Is this a BUG FIX or a FEATURE ?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
/kind cleanup
> /kind feature
> /kind design
> /kind flake
> /kind failing
> /kind documentation
> /kind regression

**What this PR does / why we need it**:
Bumping FRR to 9.1.0

**Special notes for your reviewer**:

**Release note**:

```release-note
Bump FRR to version 9.1.0
```

### CODE REVIEW

**Comment by karampok** [comment]
```
[I] kka@f-t14s ~/w/g/m/frr-k8s (bumpfrr10 ✔)> rg "9\.0\.2"
RELEASE_NOTES.md
17:- FRR: bump to 9.0.2, allow to peer with localhost ([PR 118](https://github.com/metallb/frr-k8s/pull/118))

internal/frr/docker_test.go
27:     frrImageTag = "9.0.2"

hack/demo/demo.sh
16:docker run -d --privileged --network kind --rm --ulimit core=-1 --name frr --volume "$FRR_CONFIG":/etc/frr quay.io/frrouting/frr:9.0.2
```
any of this references to older frr image should be updated? I suppose the RELEASE note entry is added when releasing.

**Comment by karampok** [comment]
Why you do not bump in the latest frr?
```
skopeo list-tags docker://quay.io/frrouting/frr
{
    "Repository": "quay.io/frrouting/frr",
    "Tags": [
        "10.0.0",
        "10.0.1",
```
if there is a reason could we add it in the description of the commit?

**Comment by fedepaol** [comment]
> ```
> [I] kka@f-t14s ~/w/g/m/frr-k8s (bumpfrr10 ✔)> rg "9\.0\.2"
> RELEASE_NOTES.md
> 17:- FRR: bump to 9.0.2, allow to peer with localhost ([PR 118](https://github.com/metallb/frr-k8s/pull/118))
> 
> internal/frr/docker_test.go
> 27:     frrImageTag = "9.0.2"
> 
> hack/demo/demo.sh
> 16:docker run -d --privileged --network kind --rm --ulimit core=-1 --name frr --volume "$FRR_CONFIG":/etc/frr quay.io/frrouting/frr:9.0.2
> ```
> 
> any of this references to older frr image should be updated? I suppose the RELEASE note entry is added when releasing.
 
Good catch!

**Comment by fedepaol** [comment]
> Why you do not bump in the latest frr?
> 
> ```
> skopeo list-tags docker://quay.io/frrouting/frr
> {
>     "Repository": "quay.io/frrouting/frr",
>     "Tags": [
>         "10.0.0",
>         "10.0.1",
> ```
> 
> if there is a reason could we add it in the description of the commit?

I tried the latest, CI started failing for no clear reasons, so I assume latest is not super stable and went to the previous generation which still fixes my problem with importing vrfs.
I'll leave a comment.

**Comment by karampok** [comment]
Ack, then maybe you could state that not bumping to latest due to ci is failing), and what is the reason you bump (fixes my problem, which problem?)

Also we could have an issue "bump to FRR 10" to follow it

**Comment by fedepaol** [comment]
> Ack, then maybe you could state that not bumping to latest due to ci is failing), and what is the reason you bump (fixes my problem, which problem?)
>

I won't state why I am not bumping on a later version as it might be obsoleted / fixed when we look at it in the future.
Hopefully, 10.x will be stable and pass in our CI in the future.

**Comment by fedepaol** [comment]
> Also we could have an issue "bump to FRR 10" to follow it

Filed https://github.com/metallb/frr-k8s/issues/165 , but not sure I want us to work / bump on that any time soon.

**Review by karampok — APPROVED** [review]

**Pull request merged**
