### PR TITLE
Fix CI failure on publish workflow and small clean up 

### PR DESCRIPTION
**Pull request by karampok**
/kind cleanup
/kind feature

I observe that CI is failing on publish/unit-tests [ci](https://github.com/metallb/frr-k8s/actions/runs/8650911596/job/23742939501). This is probably going to happen again.
I am not sure why not failing in ci workflow.

Also some small changes in the ci.yaml

### CODE REVIEW

**Comment by karampok** [comment]
Do you know how/when the zz_generated.deepcopy.go is re-created?
```
rm api/v1beta1/zz_generated.deepcopy.go
[I] kka@f-t14s ~/w/g/m/frr-k8s (dev ✖1)> make manifests
test -s /home/kka/workspace/github.com/metallb/frr-k8s/bin/controller-gen && /home/kka/workspace/github.com/metallb/frr-k8s/bin/controller-gen --version | grep -q v0.14.0 || \
GOBIN=/home/kka/workspace/github.com/metallb/frr-k8s/bin go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.14.0
/home/kka/workspace/github.com/metallb/frr-k8s/bin/controller-gen rbac:roleName=daemon-role crd webhook paths="./..." output:crd:artifacts:config=config/crd/bases
cp config/crd/bases/*.yaml charts/frr-k8s/charts/crds/templates
[I] kka@f-t14s ~/w/g/m/frr-k8s (dev ✖1)> ls api/v1beta1/zz_generated.deepcopy.go
ls: cannot access 'api/v1beta1/zz_generated.deepcopy.go': No such file or directory
```

**Comment by karampok** [comment]
I think the ` make generate` is not being run in ci workflow followed by a `make checkuncommited`

**Comment by fedepaol** [comment]
> Do we still need this file https://github.com/metallb/frr-k8s/blob/main/.github/workflows/cancel.yaml?

I guess we don't. Can you please check if we removed it on metallb too?

**Comment by fedepaol** [comment]
> I think the ` make generate` is not being run in ci workflow followed by a `make checkuncommited`
 
Yep, mind adding it?

**Comment by fedepaol** [comment]
> I have added the `make generate` in the check-generate job. Cancel.yml is gone (as in metallb) Do we need this https://github.com/metallb/frr-k8s/blob/main/.github/workflows/publish.yaml#L55-L56 QEMU?

I'd leave it / test if we don't need it in a separate PR.

**Pull request merged**
