### PR TITLE
Adding BFD to Graceful Restart fails

### PR DESCRIPTION
**Pull request by karampok**
/kind bug

-->

```release-note
NONE
```

```
Establish BGP session with EnableGracefulRestart When restarting the frrk8s deamon pods external BGP peer maintains routes IPV4
/home/kka/workspace/github.com/metallb/frr-k8s/e2etests/tests/graceful_restart.go:171
  STEP: Start GR test @ 10/24/24 11:19:24.717
  STEP: 0 Neigh ebgp-single-hop does not have prefix 5.5.5.5/32: routerForCIDR: route not found for dst prefix 5.5.5.5/32 @ 10/24/24 11:19:38.038
  STEP: 0 Neigh ebgp-single-hop does not have prefix 5.5.5.5/32: routerForCIDR: route not found for dst prefix 5.5.5.5/32 @ 10/24/24 11:19:38.209
  STEP: 1 Neigh ebgp-single-hop does have prefix 5.5.5.5/32: %!s(<nil>) @ 10/24/24 11:19:39.389
  STEP: 2 Neigh ebgp-single-hop does have prefix 5.5.5.5/32: %!s(<nil>) @ 10/24/24 11:19:39.564
  STEP: 3 Neigh ebgp-single-hop does have prefix 5.5.5.5/32: %!s(<nil>) @ 10/24/24 11:19:39.748
  STEP: 4 Neigh ebgp-single-hop does have prefix 5.5.5.5/32: %!s(<nil>) @ 10/24/24 11:19:39.927
  [FAILED] in [It] - /home/kka/workspace/github.com/metallb/frr-k8s/e2etests/tests/graceful_restart.go:168 @ 10/24/24 11:19:39.927
• [FAILED] [62.740 seconds]
Establish BGP session with EnableGracefulRestart When restarting the frrk8s deamon pods external BGP peer maintains routes [It] IPV4
/home/kka/workspace/github.com/metallb/frr-k8s/e2etests/tests/graceful_restart.go:171

  [FAILED] Failed after 15.210s.
  route check failed during frr-k8s-pod reboot
  Unexpected error:
      <*errors.joinError | 0xc00060af48>:
      Neigh ebgp-single-hop does not have prefix 5.5.5.5/32: routerForCIDR: route not found for dst prefix 5.5.5.5/32
      {
          errs: [
              <*fmt.wrapError | 0xc0005175a0>{
                  msg: "Neigh ebgp-single-hop does not have prefix 5.5.5.5/32: routerForCIDR: route not found for dst prefix 5.5.5.5/32",
                  err: <*fmt.wrapError | 0xc000517580>{
                      msg: "routerForCIDR: route not found for dst prefix 5.5.5.5/32",
                      err: <routes.RouteNotFoundError>{Route: "5.5.5.5/32"},
                  },
              },
          ],
      }
  occurred
  In [It] at: /home/kka/workspace/github.com/metallb/frr-k8s/e2etests/tests/graceful_restart.go:168 @ 10/24/24 11:19:39.927
````

Routes are gone for < second

### CODE REVIEW

**Comment by karampok** [comment]
The behavior of sending BFD Cease seems default on start up. For example looking the logs from the very first start of the frr-k8s-daemon 

```
2024/10/25 08:28:29.132 ZEBRA: [V0KXZ-QFE4D] bfd_dst_update msg from client bfd: length=25
2024/10/25 08:28:29.132 BGP: [HZN6M-XRM1G] %NOTIFICATION: sent to neighbor 172.18.0.6 6/10 (Cease/BFD Down) 0 bytes 
2024/10/25 08:28:29.132 BFD: [YA0Q5-C0BPV] control-packet: 'remote discriminator' is zero, not overridden [mhop:no peer:172.18.0.6 local:172.18.0.3 port:3434]
2024/10/25 08:28:29.132 BGP: [ZWCSR-M7FG9] 172.18.0.6 [FSM] BGP_Stop (Established->Clearing), fd 22
```
and the BGP peering happens twice,
```
2024/10/25 08:28:26.123 BGP: [HKWM3-ZC5QP] 172.18.0.3 fd 23 went from Active to Connect
2024/10/25 08:28:26.123 BGP: [HKWM3-ZC5QP] 172.18.0.3 fd 23 went from Connect to OpenSent
2024/10/25 08:28:29.131 BGP: [HKWM3-ZC5QP] 172.18.0.3 fd 23 went from Idle to Active
2024/10/25 08:28:29.131 BGP: [HKWM3-ZC5QP] 172.18.0.3 fd 23 went from Active to OpenSent
2024/10/25 08:28:29.131 BGP: [HKWM3-ZC5QP] 172.18.0.3 fd 23 went from OpenSent to OpenConfirm
2024/10/25 08:28:29.132 BGP: [HKWM3-ZC5QP] 172.18.0.3 fd 23 went from OpenConfirm to Established

2024/10/25 08:28:29.132 BGP: [HZN6M-XRM1G] %NOTIFICATION: received from neighbor 172.18.0.3 6/10 (Cease/BFD Down) 0 bytes

2024/10/25 08:28:31.133 BGP: [HKWM3-ZC5QP] 172.18.0.3 fd 23 went from Idle to Active
2024/10/25 08:28:31.133 BGP: [HKWM3-ZC5QP] 172.18.0.3 fd 23 went from Active to OpenSent
2024/10/25 08:28:31.133 BGP: [HKWM3-ZC5QP] 172.18.0.3 fd 23 went from OpenSent to OpenConfirm
2024/10/25 08:28:31.133 BGP: [HKWM3-ZC5QP] 172.18.0.3 fd 23 went from OpenConfirm to Established
```

**Comment by fedepaol** [comment]
Can you describe the sequence of events that you are seeing on each side when an frr-k8s pod is restarted? I am a bit lost.

**Comment by fedepaol** [comment]
```
# Routes are removes due to peer removed, no GR timer here  event 4
10:02:18.518 BGP: [G7K80-KF0HM] Tx route delete VRF 0 5.5.5.5/32
```

Are you sure this ^^^ is from the external peer logs? Asking because this says "tx route delete" with the prefixes we configure locally.

Also also, could it be that we are hitting https://github.com/FRRouting/frr/issues/12030 ?

**Comment by fedepaol** [comment]
> Not sure I undestand
> 
> > "tx route delete" with the prefixes we configure locally.
> > what is locally?

locally -> on frr-k8s. We don't have those in the external frr

**Comment by karampok** [comment]
I have added 5.5.5.5 for adv prefix to be easier to grep https://github.com/metallb/frr-k8s/blob/9b76ac5f2def0097463635e7f11b07c11f0aca60/e2etests/tests/graceful_restart.go#L174
and therefore there is this route in the external peer
```
cat kind-logs-ipv4-manifests/Establish_BGP_session_with_EnableGracefulRestart_When_restarting_the_frrk8s_deamon_pods_external_BGP_peer_maintains_routes_IPV4-failed/frrdump-ebgp-single-hop.log |grep 5.5.5.5 |grep delete
2024/10/28 10:02:18.518 BGP: [G7K80-KF0HM] Tx route delete VRF 0 5.5.5.5/32
```

**Comment by fedepaol** [comment]
Is this log

```
Graceful restart configuration changed, reset this peer to take effect
% The Graceful Restart command used is not valid at this moment.
line 141: Failure to communicate[13] to bgpd, line:  neighbor 172.18.0.5 graceful-restart

[271|staticd] done
[254|mgmtd] done
[261|bgpd] Configuration file[/etc/frr/frr.conf] processing failure: 13
[272|bfdd] done
[255|zebra] done
2024-10-28 10:02:14,466 [91mWARNING[0m: frr-reload.py failed due to
vtysh (exec file) exited with status 13
Failed to fully apply configuration file 1 seconds
```

**Comment by karampok** [comment]
> What I find odd is the fact that it should be frr-k8s to transmit the route delete, not the external frr.

AFAICT the delete happens because BFD Cease make the peering down. And then all routes are removed.


> % The Graceful Restart command used is not valid at this moment.
I think this is error is due to the following bug and is not important

https://github.com/FRRouting/frr/issues/15880

but it worth double checking

**Comment by fedepaol** [comment]
I thnk the key is here:

```
2024/10/28 10:02:18.457 ZEBRA: [G37DH-KRAE9] bfd_dst_register msg from client bgp: length=40



2024/10/28 10:02:18.457 BFD: [MSVDW-Y8Z5Q] ptm-del-dest: deregister peer [mhop:no peer:172.18.0.5 local:0.0.0.0 vrf:default cbit:0x00 minimum-ttl:255 profile:simple]
2024/10/28 10:02:18.457 BFD: [NYF5K-SE3NS] ptm-del-session: [mhop:no peer:172.18.0.5 local:0.0.0.0 vrf:default] refcount=0
2024/10/28 10:02:18.457 BFD: [NW21R-MRYNT] session-delete: mhop:no peer:172.18.0.5 local:0.0.0.0 vrf:default
2024/10/28 10:02:18.457 BFD: [YA0Q5-C0BPV] control-packet: no session found [mhop:no peer:172.18.0.5 local:172.18.0.3 port:7]
2024/10/28 10:02:18.457 BFD: [MSVDW-Y8Z5Q] ptm-add-dest: register peer [mhop:no peer:172.18.0.5 local:172.18.0.3 vrf:default cbit:0x00 minimum-ttl:255 profile:simple]



2024/10/28 10:02:18.457 BFD: [PSB4R-8T1TJ] session-new: mhop:no peer:172.18.0.5 local:172.18.0.3 vrf:default ifname:eth0
2024/10/28 10:02:18.457 ZEBRA: [V0KXZ-QFE4D] bfd_dst_update msg from client bfd: length=25
2024/10/28 10:02:18.457 BGP: [Q4BCV-6FHZ5] zclient_bfd_session_update: 172.18.0.3/32 -> 172.18.0.5/32 (interface eth0) VRF default(0) (CPI bit no): Down
2024/10/28 10:02:18.457 BGP: [MKVHZ-7MS3V] bfd_session_status_update: neighbor 172.18.0.5 vrf default(0) bfd state Up -> Down
```

If you look, the details of the session change (local, interface). It's also clear that a bfd control message is discarderd in the meanwhile. We need to understand why it's happening (and doesn't seem related to GR).

**Comment by karampok** [comment]
So you suggest that: 

```
frr-k8s-daemon-2lgbt.log |grep BFD|grep session-new
2024/10/28 10:02:14.271 BFD: [PSB4R-8T1TJ] session-new: mhop:no peer:172.18.0.5 local:0.0.0.0 vrf:default
2024/10/28 10:02:18.457 BFD: [PSB4R-8T1TJ] session-new: mhop:no peer:172.18.0.5 local:172.18.0.3 vrf:default ifname:eth0
```
 when the session is updated (session-delete and session-new logs) the BFD Down notification fires.  That can be indeed, but is unclear why local/interface is not fixed since start but is updated later (and based on what input)

**Comment by fedepaol** [comment]
> So you suggest that:
> 
> ```
> frr-k8s-daemon-2lgbt.log |grep BFD|grep session-new
> 2024/10/28 10:02:14.271 BFD: [PSB4R-8T1TJ] session-new: mhop:no peer:172.18.0.5 local:0.0.0.0 vrf:default
> 2024/10/28 10:02:18.457 BFD: [PSB4R-8T1TJ] session-new: mhop:no peer:172.18.0.5 local:172.18.0.3 vrf:default ifname:eth0
> ```
> 
> when the session is updated (session-delete and session-new logs) the BFD Down notification fires. That can be indeed, but is unclear why local/interface is not fixed since start but is updated later (and based on what input)

Can you give a shot replacing the frr image with :master to see if something changes along the way?

**Comment by karampok** [comment]
@fedepaol same failure with the master tag. I have also tried any combination of passive/active neither this helps. Let me know if you have any suggestion how to dig deeper. Thanks

**Comment by karampok** [comment]
I have opened this https://github.com/metallb/frr-k8s/pull/219 which demonstrates the issue without GR.

**Pull request closed without merging**
